import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { IconChevronRight } from '@tabler/icons-react'


export default function Home() {
  return (
    <>
      <Head>
        <title>Invoicer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='padding_container'>
          <nav className={styles.nav}>
            <div>All Services For Invoice <span className={styles.badge}>Invoice</span></div>
            <div>
            </div>
          </nav>
          <div className={styles.hero_container}>
            <div className={styles.hero}>
              <div className={styles.hero_text}>
                <div className={styles.titlespan}>
                  <h1 className={styles.title}>Simplify Your Invoicing with AmsTechs</h1>
                </div>
                <p style={{fontSize:12,fontWeight:500}}>Say goodbye to the hassle of manual invoicing and payment tracking. [Your Company Name] offers a seamless and automated solution that saves you time and ensures accuracy. Fill out the form below to learn more and start streamlining your invoicing process today.</p>
                <br/>
                <div className={styles.hero_button}>
                  <button className={styles.button_light}>Interest <IconChevronRight size={18}/></button>
                </div>

              </div>
          <div className={styles.hero_form}>
hello
          </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
