import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Invoicer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav style={styles.nav}>
          <div>All Services For Invoice</div>
          <div>
            <button>Interest</button>
          </div>
        </nav>
      </main>
    </>
  )
}
